# Generated by Django 5.1.15 on 2026-06-23 06:20

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0004_business_public_profile_fields"),
        ("qr", "0002_alter_qrcodetoken_type"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="campaigns/"),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("visit", "Visit"),
                            ("time_window", "Time window"),
                            ("group", "Group"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("active_days", models.JSONField(blank=True, default=list)),
                ("active_start_time", models.TimeField(default=datetime.time(0, 0))),
                ("active_end_time", models.TimeField(default=datetime.time(23, 59))),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_rewards", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "completion_limit_per_customer",
                    models.CharField(
                        choices=[("once", "Once"), ("repeatable", "Repeatable")],
                        default="once",
                        max_length=32,
                    ),
                ),
                ("auto_join_enabled", models.BooleanField(default=False)),
                (
                    "allow_multiple_campaign_counting",
                    models.BooleanField(default=False),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("redeemed", "Redeemed"),
                        ],
                        default="joined",
                        max_length=32,
                    ),
                ),
                ("progress_count", models.PositiveIntegerField(default=0)),
                ("completion_cycle", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_progress_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("visit", "Visit"),
                            ("group_checkin", "Group check-in"),
                            ("referral", "Referral"),
                        ],
                        default="visit",
                        max_length=32,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("staff_scan", "Staff scan"),
                            ("staff_manual", "Staff manual"),
                            ("auto_join", "Auto join"),
                        ],
                        default="staff_scan",
                        max_length=32,
                    ),
                ),
                ("action_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("counted", "Counted"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="counted",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_actions",
                        to="businesses.business",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_actions",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="campaigns.campaignparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("free_item", "Free item"),
                            ("discount", "Discount"),
                            ("upgrade", "Upgrade"),
                            ("custom", "Custom"),
                        ],
                        default="free_item",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expiry_days_after_unlock",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reward_receiver_type",
                    models.CharField(
                        choices=[
                            ("leader", "Leader"),
                            ("every_member", "Every member"),
                            ("table", "Table"),
                        ],
                        default="leader",
                        max_length=32,
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignRewardVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voucher_code", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_vouchers",
                        to="businesses.business",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="campaigns.campaignparticipant",
                    ),
                ),
                (
                    "qr_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_vouchers",
                        to="qr.qrcodetoken",
                    ),
                ),
                (
                    "redeemed_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_campaign_vouchers",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="campaigns.campaignreward",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("visit_count", "Visit count"),
                            ("time_window", "Time window"),
                            ("group_checkin", "Group check-in"),
                        ],
                        max_length=32,
                    ),
                ),
                ("required_count", models.PositiveIntegerField(default=1)),
                (
                    "minimum_time_between_actions",
                    models.DurationField(blank=True, null=True),
                ),
                (
                    "max_count_per_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "required_group_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "group_checkin_window_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("window_before_time", models.TimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Forming"),
                            ("full", "Full"),
                            ("checking_in", "Checking in"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="forming",
                        max_length=32,
                    ),
                ),
                ("required_size", models.PositiveIntegerField()),
                ("invite_token", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_sessions",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "group_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_group_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupSessionMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("checked_in", "Checked in"),
                            ("left", "Left"),
                            ("no_show", "No show"),
                        ],
                        default="joined",
                        max_length=32,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_session_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="campaigns.groupsession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["business", "status"], name="campaigns_c_busines_8ad052_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "campaign_type"], name="campaigns_c_status_f8002b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "start_at", "end_at"],
                name="campaigns_c_status_b38d4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignparticipant",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_c_campaig_f5e26b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignparticipant",
            index=models.Index(
                fields=["customer", "status"], name="campaigns_c_custome_66d3d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignparticipant",
            constraint=models.UniqueConstraint(
                fields=("campaign", "customer"), name="unique_campaign_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignaction",
            index=models.Index(
                fields=["campaign", "customer", "action_time"],
                name="campaigns_c_campaig_4eeff9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignaction",
            index=models.Index(
                fields=["participant", "action_time"],
                name="campaigns_c_partici_9fc7d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignaction",
            index=models.Index(
                fields=["verified_by_staff", "action_time"],
                name="campaigns_c_verifie_912324_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrewardvoucher",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_c_campaig_683ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrewardvoucher",
            index=models.Index(
                fields=["customer", "status"], name="campaigns_c_custome_68052e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrewardvoucher",
            index=models.Index(
                fields=["status", "expires_at"], name="campaigns_c_status_b85ae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsession",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_g_campaig_881961_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsessionmember",
            constraint=models.UniqueConstraint(
                fields=("group_session", "customer"), name="unique_group_session_member"
            ),
        ),
    ]
