# Generated by Django 5.1.15 on 2026-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ending_warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrewardvoucher",
            name="expiry_warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
