# Generated by Django 5.1.15 on 2026-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="group",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="group",
            name="visit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
