# Generated by Django 5.1.15 on 2026-06-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0010_business_is_demo_business_is_paid_and_more"),
        ("campaigns", "0002_group_name_group_note_group_visit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignparticipant",
            name="points_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignreward",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="businesses.catalogitem",
            ),
        ),
        migrations.AddField(
            model_name="campaignreward",
            name="item_selection",
            field=models.CharField(
                blank=True,
                choices=[("fixed", "Fixed item"), ("customer", "Customer chooses")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignrewardvoucher",
            name="cashback_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaignrewardvoucher",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="businesses.catalogitem",
            ),
        ),
        migrations.AddField(
            model_name="campaignrule",
            name="cashback_per_point",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaignrule",
            name="points_basis",
            field=models.CharField(
                blank=True,
                choices=[("visit", "Per visit"), ("spend", "Per spend")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignrule",
            name="points_per_som",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaignrule",
            name="points_per_visit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaignreward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("free_item", "Free item"),
                    ("discount", "Discount"),
                    ("upgrade", "Upgrade"),
                    ("custom", "Custom"),
                    ("cashback", "Cashback"),
                ],
                default="free_item",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="mechanic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("visit", "Visit"),
                    ("stamp", "Stamp"),
                    ("spend", "Spend"),
                    ("points", "Points"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
