# Generated by Django 5.1.15 on 2026-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_campaignparticipant_points_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignparticipant",
            name="current_spend",
        ),
        migrations.RemoveField(
            model_name="campaignparticipant",
            name="points_balance",
        ),
        migrations.RemoveField(
            model_name="campaignrewardvoucher",
            name="cashback_amount",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="cashback_per_point",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="max_banked",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="min_spend",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="points_basis",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="points_per_som",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="points_per_visit",
        ),
        migrations.RemoveField(
            model_name="campaignrule",
            name="required_spend",
        ),
        migrations.AlterField(
            model_name="campaignreward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("free_item", "Free item"),
                    ("discount", "Discount"),
                    ("upgrade", "Upgrade"),
                    ("custom", "Custom"),
                ],
                default="free_item",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="mechanic",
            field=models.CharField(
                blank=True, choices=[("visit", "Visit")], max_length=32, null=True
            ),
        ),
    ]
