# Generated by Django 5.1.15 on 2026-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_active_groups_per_user",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Maximum number of active group deals a customer can belong to at the same time.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System configuration",
                "verbose_name_plural": "System configuration",
            },
        ),
    ]
