# Generated by Django 5.1.15 on 2026-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='trial_period_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Length of the free trial (days) applied to a business when it is approved.'),
        ),
    ]
