# Generated by Django 5.1.15 on 2026-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemconfiguration_trial_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Instagram link shown in the footer of outgoing emails.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='support_email',
            field=models.EmailField(blank=True, default='', help_text='Support contact address shown in the footer of outgoing emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='telegram_url',
            field=models.URLField(blank=True, default='', help_text='Telegram link shown in the footer of outgoing emails.'),
        ),
    ]
