# Generated by Django 5.1.15 on 2026-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="campaign_updates",
            field=models.BooleanField(default=True),
        ),
    ]
