"use client";

import { useCatalog, useCreateLoyaltyProgram, type LoyaltyType } from "@jaqyn/api";
import { useT } from "@jaqyn/i18n";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { OwnerShell } from "../../_components/OwnerShell";

export default function NewLoyaltyPage() {
  const t = useT(); const router = useRouter(); const create = useCreateLoyaltyProgram(); const catalog = useCatalog(); const [type, setType] = useState<LoyaltyType | null>(null); const [name, setName] = useState(""); const [basis, setBasis] = useState<"visit" | "spend">("spend"); const [rate, setRate] = useState("0.05"); const [cashback, setCashback] = useState("1"); const [minimum, setMinimum] = useState("10"); const [target, setTarget] = useState("6"); const [maxBanked, setMaxBanked] = useState("2"); const [reward, setReward] = useState(""); const [itemMode, setItemMode] = useState<"fixed" | "customer">("customer"); const [item, setItem] = useState("");
  const submit = () => { if (!type) return; create.mutate({ type, name, description: "", ...(type === "points" ? { points_basis: basis, points_per_visit: basis === "visit" ? Number(rate) : null, points_per_som: basis === "spend" ? rate : null, cashback_per_point: cashback, min_redeem_points: Number(minimum) } : { required_count: Number(target), max_banked: type === "stamp" ? Number(maxBanked) : null, reward_type: "free_item", reward_title: reward, reward_description: "", reward_expiry_days: 30, item_selection: itemMode, catalog_item_id: itemMode === "fixed" ? item : null }) }, { onSuccess: (program) => router.push(`/business/loyalty/${program.id}`) }); };
  return <OwnerShell title={t("loyalty.biz.new")}><h1 className="font-display text-2xl font-bold">{t("loyalty.biz.chooseType")}</h1><div className="mt-4 grid gap-3 sm:grid-cols-3">{(["points", "stamp", "visit"] as LoyaltyType[]).map((value) => <button key={value} onClick={() => setType(value)} className={`rounded-2xl border p-5 text-left font-bold ${type === value ? "border-brand bg-brand-muted" : "border-line bg-card"}`}>{t(`loyalty.biz.${value}`)}</button>)}</div>{type && <div className="mt-6 max-w-xl space-y-4 rounded-2xl border border-line bg-card p-5"><Field label={t("loyalty.biz.name")} value={name} set={setName} />{type === "points" ? <><label className="block text-sm font-semibold">{t("loyalty.biz.basis")}<select value={basis} onChange={(e) => setBasis(e.target.value as "visit" | "spend")} className="mt-1 w-full rounded-xl border border-line p-3"><option value="visit">{t("loyalty.biz.perVisit")}</option><option value="spend">{t("loyalty.biz.perSpend")}</option></select></label><Field label={t("loyalty.biz.rate")} value={rate} set={setRate} /><Field label={t("loyalty.biz.cashbackRate")} value={cashback} set={setCashback} /><Field label={t("loyalty.biz.minimum")} value={minimum} set={setMinimum} /><p className="text-sm text-subtle">{(Number(rate) * Number(cashback) * 100).toFixed(1)}% back</p></> : <><Field label={t("loyalty.biz.target")} value={target} set={setTarget} />{type === "stamp" && <Field label={t("loyalty.biz.maxBanked")} value={maxBanked} set={setMaxBanked} />}<Field label={t("loyalty.biz.reward")} value={reward} set={setReward} /><select value={itemMode} onChange={(e) => setItemMode(e.target.value as "fixed" | "customer")} className="w-full rounded-xl border border-line p-3"><option value="customer">Customer choice</option><option value="fixed">Fixed item</option></select>{itemMode === "fixed" && <select value={item} onChange={(e) => setItem(e.target.value)} className="w-full rounded-xl border border-line p-3"><option value="">—</option>{(catalog.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select>}</>}<button onClick={submit} disabled={!name || create.isPending} className="w-full rounded-xl bg-brand py-3 font-bold text-white disabled:opacity-50">{t("loyalty.biz.create")}</button></div>}</OwnerShell>;
}
function Field({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label className="block text-sm font-semibold">{label}<input value={value} onChange={(e) => set(e.target.value)} className="mt-1 w-full rounded-xl border border-line p-3" /></label>; }
