# Generated by Django 5.1.15 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
