# Generated by Django 5.1.15 on 2026-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customerprofile_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_emoji",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
