# Generated by Django 5.1.15 on 2026-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_email_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
