# Generated by Django 5.1.15 on 2026-06-28 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0010_business_is_demo_business_is_paid_and_more"),
        ("qr", "0003_alter_qrcodetoken_type"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("stamp", "Stamp"),
                            ("visit", "Visit"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="loyalty/"),
                ),
                (
                    "points_basis",
                    models.CharField(
                        blank=True,
                        choices=[("visit", "Per visit"), ("spend", "Per spend")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "points_per_visit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "points_per_som",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cashback_per_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_redeem_points",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("required_count", models.PositiveIntegerField(blank=True, null=True)),
                ("max_banked", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reward_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free_item", "Free item"),
                            ("discount", "Discount"),
                            ("upgrade", "Upgrade"),
                            ("cashback", "Cashback"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("reward_title", models.CharField(blank=True, max_length=160)),
                ("reward_description", models.TextField(blank=True)),
                ("reward_expiry_days", models.PositiveIntegerField(default=30)),
                (
                    "item_selection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed item"),
                            ("customer", "Customer chooses"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("active_days", models.JSONField(blank=True, default=list)),
                ("active_start_time", models.TimeField(blank=True, null=True)),
                ("active_end_time", models.TimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_programs",
                        to="businesses.business",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="businesses.catalogitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("stamps_count", models.PositiveIntegerField(default=0)),
                ("visits_count", models.PositiveIntegerField(default=0)),
                ("points_balance", models.PositiveIntegerField(default=0)),
                (
                    "current_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cycle", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earn", "Earn"),
                            ("redeem", "Redeem"),
                            ("adjust", "Adjust"),
                            ("reverse", "Reverse"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("staff_scan", "Staff scan"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="staff_scan",
                        max_length=16,
                    ),
                ),
                ("points_delta", models.IntegerField(blank=True, null=True)),
                ("stamps_delta", models.IntegerField(blank=True, null=True)),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="loyalty.loyaltymembership",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoyaltyVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voucher_code", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("free_item", "Free item"),
                            ("discount", "Discount"),
                            ("upgrade", "Upgrade"),
                            ("cashback", "Cashback"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reward_title", models.CharField(blank=True, max_length=160)),
                (
                    "cashback_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_warned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="businesses.business",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="businesses.catalogitem",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="loyalty.loyaltymembership",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "qr_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qr.qrcodetoken",
                    ),
                ),
                (
                    "redeemed_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.staffmember",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="loyaltyprogram",
            index=models.Index(
                fields=["business", "status"], name="loyalty_loy_busines_359328_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyprogram",
            index=models.Index(
                fields=["status", "type"], name="loyalty_loy_status_617d37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltymembership",
            constraint=models.UniqueConstraint(
                fields=("program", "customer"), name="uniq_loyalty_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyvoucher",
            index=models.Index(
                fields=["customer", "status"], name="loyalty_loy_custome_99e52a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyvoucher",
            index=models.Index(
                fields=["business", "status"], name="loyalty_loy_busines_354cfd_idx"
            ),
        ),
    ]
