# Generated by Django 5.1.15 on 2026-07-05 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("min_visits", models.PositiveIntegerField()),
                (
                    "cashback_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["min_visits"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "min_visits"),
                        name="uniq_loyalty_tier_threshold",
                    )
                ],
            },
        ),
    ]
