# Generated by Django 5.1.15 on 2026-06-16 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupoffer",
            name="checkin_window_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="max_group_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="max_groups_per_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="min_paid_customers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="min_spend_per_person",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="requires_staff_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="requires_staff_code",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("free_shared_item", "Free shared item"),
                    ("group_discount", "Group discount"),
                    ("leader_reward", "Leader reward"),
                    ("buy_x_get_y", "Buy X get Y"),
                    ("friend_booking", "Friend booking"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="time_end",
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="time_start",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="valid_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="valid_from",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="groupoffer",
            name="valid_to",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="groupoffer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending approval"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("expired", "Expired"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
