# Generated by Django 5.1.15 on 2026-06-16 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_groupoffer_checkin_window_minutes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupdeal",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupdeal",
            name="redeemed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupdeal",
            name="reward_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="groupdeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("forming", "Forming"),
                    ("full", "Full"),
                    ("scheduled", "Scheduled"),
                    ("checking_in", "Checking in"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="forming",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("checked_in", "Checked in"),
                            ("left", "Left"),
                            ("no_show", "No show"),
                            ("removed", "Removed"),
                        ],
                        default="joined",
                        max_length=32,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.groupdeal",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_deal", "customer"), name="unique_group_member"
                    )
                ],
            },
        ),
    ]
