# Generated by Django 5.1.15 on 2026-06-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr", "0002_alter_qrcodetoken_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodetoken",
            name="type",
            field=models.CharField(
                choices=[
                    ("merchant_collect", "Merchant collect"),
                    ("customer_profile", "Customer profile"),
                    ("reward_redeem", "Reward redeem"),
                    ("group_invite", "Group invite"),
                    ("group_checkin", "Group check-in"),
                    ("group_reward", "Group reward"),
                    ("campaign", "Campaign"),
                    ("campaign_reward", "Campaign reward"),
                    ("loyalty_reward", "Loyalty reward"),
                ],
                max_length=32,
            ),
        ),
    ]
