# Generated by Django 5.1.15 on 2026-07-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qr", "0003_alter_qrcodetoken_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApprovalCode",
        ),
    ]
