# Generated by Django 5.1.15 on 2026-06-17 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_business_business_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("glyph", models.CharField(blank=True, max_length=8)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("menu", "Menu"),
                            ("services", "Services"),
                            ("products", "Products"),
                            ("plans", "Plans"),
                        ],
                        default="services",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="business",
            name="change_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="business",
            name="country",
            field=models.CharField(blank=True, default="Kyrgyzstan", max_length=128),
        ),
        migrations.AddField(
            model_name="business",
            name="cover_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="business",
            name="default_currency",
            field=models.CharField(blank=True, default="KGS", max_length=16),
        ),
        migrations.AddField(
            model_name="business",
            name="default_language",
            field=models.CharField(blank=True, default="en", max_length=8),
        ),
        migrations.AddField(
            model_name="business",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="business",
            name="logo_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="business",
            name="menu_style",
            field=models.CharField(blank=True, default="Card grid", max_length=64),
        ),
        migrations.AddField(
            model_name="business",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("in_progress", "In progress"),
                    ("submitted", "Submitted"),
                    ("changes_requested", "Changes requested"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="public_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="timezone",
            field=models.CharField(blank=True, default="Asia/Bishkek", max_length=64),
        ),
        migrations.AddField(
            model_name="business",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Pending verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending_verification",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="visibility_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("hidden", "Hidden"),
                    ("published", "Published"),
                    ("unpublished", "Unpublished"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="business",
            name="area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="business",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cafe", "Cafe"),
                    ("restaurant", "Restaurant"),
                    ("barber", "Barber"),
                    ("beauty", "Beauty"),
                    ("retail", "Retail"),
                    ("bakery", "Bakery"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_business",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="BusinessOwnerInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_invites",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(default="menu", max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("price", models.CharField(blank=True, max_length=64)),
                ("duration", models.CharField(blank=True, max_length=64)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_items",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("contact", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(blank=True, max_length=128)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invites",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
