# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_businesstype_business_business_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="accent_color",
            field=models.CharField(blank=True, default="#C25E3C", max_length=16),
        ),
        migrations.AddField(
            model_name="business",
            name="glyph",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="business",
            name="price_level",
            field=models.CharField(blank=True, default="cc", max_length=8),
        ),
        migrations.AddField(
            model_name="business",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
