# Generated by Django 5.1.15 on 2026-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_public_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="pending_owner_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="pending_owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
