# Generated by Django 5.1.15 on 2026-06-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0008_businessnote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Business", "verbose_name_plural": "Businesses"},
        ),
    ]
