# Generated by Django 5.1.15 on 2026-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_alter_business_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
