# Generated by Django 5.1.15 on 2026-07-02 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0010_business_is_demo_business_is_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PitchInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("opened", "Opened"),
                            ("claimed", "Claimed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("chosen_goal", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "chosen_reward_text",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitch_invites",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
